global:
 message: welcome to Global Microservices Environment

 spring:
  cloud:
    config:
      server:
        git:
          uri: <YOUR_GIT_REPOSITORY_URL>   # e.g., https://github.com/your-username/config-repo.git
          default-label: main               # or 'master', depending on your repo's default branch
          search-paths: '{application}'     # Tells the server to look for configs in subdirectories named after the application

logging:
 level:
  root: INFO

management:
 endpoints:
  web:
   exposure: 
    include : health, info, refresh
 endpoint:
  health:
   show-details: always

 
 
 
