global:
 message: welcome to Customer Service dev Environment

server:
  port: 8082

message: Hello from Customer dev!!!

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_dev
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true

  


