global:
 message: welcome to Order Service prod Environment

server:
  port: 8085

message: Hello from Order prod!!!

spring:
  application:
    name: Order-service
 datasource:
   url: jdbc:mysql://localhost:3306/order_prod
   driverClassName: com.mysql.cj.jdbc.Driver
   username: root
   password: root
  jpa:
   hibernate:
    ddl-auto: update
    show-sql: true
